### ISSUE TITLE
fix: mailing list button expands on error

### ISSUE THREAD

**Issue by jeffrey-zang** [hack-the-6ix/2024.hackthe6ix.com#16]
![image](https://github.com/hack-the-6ix/2024.hackthe6ix.com/assets/66485719/9f0a2273-5f54-4355-9b36-7dcb5315a90f)
looks weird

**Comment by fpunny** [comment]
@jeffrey-zang which device? maybe i fixed it?

**Comment by jeffrey-zang** [comment]
mac, yup fixed
